CREATE TABLE walkability
(CBSA_POP int, CBSA_EMP int,
 CBSA_WRK int, Ac_Total float,
 Ac_Water float, Ac_Land float,
 Ac_Unpr float, TotPop int,
 Count_HU float, HH float,
 P_WrkAge float, AutoOwn0 int,
 Pct_AO0 float, AutoOwn1 int,
 Pct_AO1 float, AutoOwn2p int,
 Pct_AO2p float, Workers int,
 R_LowWageWk int, R_MedWageWk int,
 R_HiWageWk int, R_PCTLOWWAGE float,
 TotEmp int, E5_Ret int, E5_Off int,
 E5_Ind int, E5_Svc int, E5_Ent int,
 E8_Ret int, E8_off int, E8_Ind int,
 E8_Svc int, E8_Ent int, E8_Ed int,
 E8_Hlth int, E8_Pub int, E_LowWageWk int,
 E_MedWageWk int, E_HiWageWk int, 
 E_PctLowWage float, D1A float,
 D1B float, D1C float, D1C5_RET float,
 D1C5_OFF float, D1C5_IND float,
 D1C5_SVC float, D1C5_ENT float,
 D1C8_RET float, D1C8_OFF float,
 D1C8_IND float, D1C8_SVC float,
 D1C8_ENT float, D1C8_ED float,
 D1C8_HLTH float, D1C8_PUB float,
 D1D float, D1_FLAG int, D2A_JPHH float,
 D2B_E5MIX float, D2B_E5MIXA float,
 D2B_E8MIX float, D2B_E8MIXA float,
 D2B_EPHHM float, D2C_TRPMX1 float, 
 D2C_TRPMX2 float, D2C_TRIPEQ float,
 D2R_JOBPOP float, D2R_WRKEMP float,
 D2A_WRKEMP float, D2C_WREMLX float,
 D3A float, D3AAO float, D3AMM float,
 D3APO float, D3B float, D3BAO float,
 D3BMM3 float, D3BMM4 float,
 D3BPO3 float, D3BPO4 float, D4A float, 
 D4B025 float, D4B050 float, D4C float,
 D4D float, D4E float, D5AR int, D5AE int,
 D5BR int, D5BE int, D5CR float,
 D5CRI float, D5CE float, D5CEI float,
 D5DR float, D5DRI float, D5DE float,
 D5DEI float, D2A_Ranked int,
 D2B_Ranked int, D3B_Ranked int,
 D4A_Ranked int, NatWalkInd float);